### ISSUE TITLE
面板伤害排行异常?

### ISSUE THREAD

**Issue by Chengzivzx** [NotIvny/yunzai-characterRank-js#2]
![21ad0ac3e1a846902458a71a729f7d25](https://github.com/NotIvny/yunzai-characterRank-js/assets/110247910/2b0d00e0-09bb-4cad-8894-4b0c1f59f286)
如图
无法正确显示排名
![{F780CF60-D48B-4f6a-A0D5-7DAABD58DACA}](https://github.com/NotIvny/yunzai-characterRank-js/assets/110247910/b1a60045-6d5e-4bb2-8719-23d9f7692c0c)

**Comment by NotIvny** [comment]
重构后端代码了，请求方式有变，更新下插件

**Comment by Chengzivzx** [comment]
已解决，插件做的很好~
